---
# defaults file for roles/srv01
wireguard_required_packages:
  - qrencode
  - iptables

wireguard_interface: "wg0"
wireguard_listenport: 51820
wireguard_address: "10.20.0.1/24"

## The path for storing keys on the server
wireguard_config_dir: "/etc/wireguard"

wireguard_dns: "8.8.8.8"
