---
# tasks file for roles/srv01
- name: Install prerequisites for WireGuard
  apt:
    name: "{{ wg_required_packages }}"
    state: present
    update_cache: true

- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Enable IPv4 forwarding in kernel
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Check if WireGuard private key already exists
  stat:
    path: "{{ wg_config_dir }}/private.key"
  register: wg_private_key_file

- name: Generate server private key if exists
  command: wg genkey
  register: wg_private_key_output
  when: not wg_private_key_file.stat.exists

- name: Save generated private key to file
  copy:
    content: "{{ wg_private_key_output.stdout }}"
    dest: "{{ wg_config_dir }}/private.key"
    owner: root
    group: root
    mode: '0600'
    when: not wg_private_key_file.exists

- name: Generate WireGuard configuration file
  template:
    src: wg0.conf.j2
    dest: "{{ wg_config_dir }}/{{ wg_interface }}.conf"
    owner: root
    group: root
    mode: '0600'
  notify: Restart WireGuard
