---
# tasks file for roles/srv01
- name: Install prerequisites for WireGuard
  ansible.builtin.apt:
    name: "{{ wireguard_required_packages }}"
    state: present
    update_cache: true

- name: Install WireGuard
  ansible.builtin.apt:
    name: wireguard
    state: present

- name: Enable IPv4 forwarding in kernel
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Check if WireGuard private key already exists
  ansible.builtin.stat:
    path: "{{ wireguard_config_dir }}/private.key"
  register: wireguard_private_key_file

- name: Generate server private key if exists
  ansible.builtin.command: wg genkey
  register: wireguard_private_key_output_raw
  when: not wireguard_private_key_file.stat.exists

- name: Get private key form output_raw
  ansible.builtin.set_fact:
    wireguard_private_key_output: "{{ wireguard_private_key_output_raw.stdout }}"
  when: not wireguard_private_key_file.stat.exists

- name: Save generated private key to file
  ansible.builtin.copy:
    content: "{{ wireguard_private_key_output }}"
    dest: "{{ wireguard_config_dir }}/private.key"
    owner: root
    group: root
    mode: '0600'
  when: not wireguard_private_key_file.stat.exists

- name: Read private key if file exists
  ansible.builtin.slurp:
    src: "{{ wireguard_config_dir }}/private.key"
  register: wireguard_private_key_base64
  when: wireguard_private_key_file.stat.exists

- name: Save key to the variable
  ansible.builtin.set_fact:
    wireguard_private_key_output: "{{ wireguard_private_key_base64['content'] | b64decode | trim }}"
  when: wireguard_private_key_file.stat.exists

- name: Generate WireGuard configuration file
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "{{ wireguard_config_dir }}/{{ wireguard_interface }}.conf"
    owner: root
    group: root
    mode: '0600'
  notify: Restart WireGuard

## tasks for wireguard_manager
- name: Copy WireGuard user creation script from template
  ansible.builtin.template:
    src: wg-add-user.sh.j2
    dest: /usr/local/bin/wg-add-user
    owner: root
    group: root
    mode: '0750'

- name: Copy WireGuard user deletion script from template
  ansible.builtin.template:
    src: wg-del-user.sh.j2
    dest: /usr/local/bin/wg-del-user
    owner: root
    group: root
    mode: '0750'