---
# tasks file for roles/srv01
- name: Install prerequisites for WireGuard
  apt:
    name: "{{ wg_required_packages }}"
    state: present
    update_cache: true

- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Enable IPv4 forwarding in kernel
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Generate the private key of the server
  command: wg genkey
  register: wg_private_key_output
  changed_when: false


