---
# tasks file for roles/srv01
- name: Install prerequisites for WireGuard
  ansible.builtin.apt:
    name: "{{ wireguard_required_packages }}"
    state: present
    update_cache: true

- name: Install WireGuard
  ansible.builtin.apt:
    name: wireguard
    state: present

- name: Enable IPv4 forwarding in kernel
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Generate WireGuard private key
  ansible.builtin.command: wg genkey
  register: wireguard_private_key_output_raw
  args:
    creates: "{{ wireguard_config_dir }}/private.key"

- name: Save generated private key to file # noqa: no-handler
  ansible.builtin.copy:
    content: "{{ wireguard_private_key_output_raw.stdout }}"
    dest: "{{ wireguard_config_dir }}/private.key"
    owner: root
    group: root
    mode: '0600'
  when: wireguard_private_key_output_raw.changed

## tasks for wireguard_manager
- name: Copy WireGuard user creation script from template
  ansible.builtin.template:
    src: wg-add-user.sh.j2
    dest: /usr/local/bin/wg-add-user
    owner: root
    group: root
    mode: '0750'

- name: Copy WireGuard user deletion script from template
  ansible.builtin.template:
    src: wg-del-user.sh.j2
    dest: /usr/local/bin/wg-del-user
    owner: root
    group: root
    mode: '0750'
