#cloud-config

users:
  - name: ubuntu
    shell: /bin/bash
    groups: sudo, docker
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7CvuNInbvoucGdJKhgvXS/vbM5PGt3SqhDo00gSOjK uname@desktop-2

package_update: true
package_upgrade: true

packages:
  - fail2ban
  - wireguard
  - git
  - curl
  - apt-transport-https
  - ca-certificates
  - gnupg
  - qrencode

write_files:
  - path: /etc/sysctl.d/99-wireguard-forward.conf
    owner: root:root
    permissions: '0644'
    content: |
      net.ipv4.ip_forward=1
      net.ipv6.conf.all.forwarding=1
  
  - path: /etc/fail2ban/jail.local
    owner: root:root
    permissions: '0644'
    content: |
      [DEFAULT]
      bantime  = 864000
      findtime = 600
      maxretry = 3
      banaction = ufw

      [sshd]
      enabled = true
      port    = ssh
      logpath = %(sshd_log)s
      backend = %(sshd_backend)s
  
  - path: /usr/local/bin/add-wg-user
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e

      if [ -z "$1" ]; then
          echo "Ошибка: Укажите имя пользователя!"
          echo "Использование: add-wg-user USER_NAME"
          exit 1
      fi

      USERNAME=$1
      CDIR="/etc/wireguard/clients/$USERNAME"

      if [ -d "$CDIR" ]; then
          echo "Ошибка: Пользователь $USERNAME уже существует!"
          exit 1
      fi

      mkdir -p "$CDIR"

      PRIV_KEY=$(wg genkey)
      PUB_KEY=$(echo "$PRIV_KEY" | wg pubkey)
      SERVER_PUB_KEY=$(cat /etc/wireguard/server_publickey)
      SERVER_IP=$(curl -s4 ifconfig.me)

      USED_IPS=$(grep -oE "10\.20\.0\.[0-9]+" /etc/wireguard/wg0.conf || true)
      for i in {2..254}; do
          if ! echo "$USED_IPS" | grep -q "10.20.0.$i"; then
              CLIENT_IP="10.20.0.$i"
              break
          fi
      done

      if [ -z "$CLIENT_IP" ]; then
          echo "Ошибка: В подсети закончились свободные IP адреса!"
          exit 1
      fi

      cat <<EOF > "$CDIR/$USERNAME.conf"
      [Interface]
      PrivateKey = $PRIV_KEY
      Address = $CLIENT_IP/32
      DNS = 8.8.8.8

      [Peer]
      PublicKey = $SERVER_PUB_KEY
      Endpoint = $SERVER_IP:51820
      AllowedIPs = 0.0.0.0/0
      PersistentKeepalive = 20
      EOF

      wg set wg0 peer "$PUB_KEY" allowed-ips "$CLIENT_IP/32"

      cat <<EOF >> /etc/wireguard/wg0.conf

      [Peer]
      # Name = $USERNAME
      PublicKey = $PUB_KEY
      AllowedIPs = $CLIENT_IP/32
      EOF

      echo "======================================================"
      echo "Пользователь $USERNAME успешно добавлен!"
      echo "Конфиг сохранен в: $CDIR/$USERNAME.conf"
      echo "======================================================"
      echo "=== QR-КОД ДЛЯ СМАРТФОНА ============================="
      qrencode -t ansiutf8 < "$CDIR/$USERNAME.conf"
      echo "======================================================"

  - path: /usr/local/bin/del-wg-user
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e

      if [ -z "$1" ]; then
          echo "Ошибка: Укажите имя пользователя для удаления!"
          echo "Использование: del-wg-user"
          exit 1
      fi

      USERNAME=$1
      CDIR="/etc/wireguard/clients/$USERNAME"

      if [ ! -d "$CDIR" ]; then
          echo "Ошибка: Пользователь $USERNAME на найден!"
          exit 1
      fi

      PUB_KEY=$(grep -A 2 "# Name = $USERNAME" /etc/wireguard/wg0.conf | grep "PublicKey" | awk '{print $3}' || true)
      LINE_NUMBER=$(grep -n "# Name = $USERNAME" /etc/wireguard/wg0.conf | cut -d: -f1)
      
      if [ -z "$PUB_KEY" ] && [ -z "$LINE_NUMBER" ]; then
          echo "Ошибка: Не удалось найти публичный ключ для пользователя $USERNAME!"
          exit 1
      fi

      wg set wg0 peer "$PUB_KEY" remove
      sed -i "$((LINE_NUMBER-1)),$((LINE_NUMBER+3))d" /etc/wireguard/wg0.conf
      rm -rf "$CDIR"

      echo "======================================================"
      echo "Пользователь $USERNAME успешно удален!"
      echo "Конфиг удален в: $CDIR/"
      echo "======================================================"

runcmd:
  - sysctl --system

  # WireGuard
  ## Генерируем ключи и конфигурационный файл wg0.conf
  - cd /etc/wireguard/
  - wg genkey | tee server_privatekey | wg pubkey > server_publickey
  - |
    cat <<EOF > wg0.conf
    [Interface]
    Address = 10.20.0.1/24
    ListenPort = 51820
    PrivateKey = $(cat server_privatekey)
    # 1. Разрешаем форвардинг из VPN наружу в интернет (через eth0)
    # 2. БЛОКИРУЕМ трафик из wg0 обратно в wg0 (клиент-клиент)
    PostUp = iptables -A FORWARD -i wg0 -o eth0 -j ACCEPT; iptables -A FORWARD -i wg0 -o wg0 -j REJECT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -D FORWARD -i wg0 -o eth0 -j ACCEPT; iptables -D FORWARD -i wg0 -o wg0 -j REJECT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    EOF

  ## Включаем и запускаем WireGuard
  - systemctl enable wg-quick@wg0
  - systemctl start wg-quick@wg0

  ## Включаем и запускаем Fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban

  ## Включаем Firewall (UFW) и жестко закрываем порты
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp comment 'SSH Port'
  - ufw allow 51820/udp comment 'WireGuard VPN Port'
  - ufw limit 1080/tcp comment 'SOCKS5 Port with Rate Limit'
  - ufw --force enable

  # Устновка Docker
  ## Создание директории для GPG-ключа
  - install -m 0755 -d /etc/apt/keyrings
  
  ## Скачивание официального GPG-ключа Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc

  ## Добавление официального репозитория Docker в источники APT
  - |
    tee /etc/apt/sources.list.d/docker.sources <<EOF
    Types: deb
    URIs: https://download.docker.com/linux/ubuntu
    Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
    Components: stable
    Architectures: $(dpkg --print-architecture)
    Signed-By: /etc/apt/keyrings/docker.asc
    EOF

  ## Обновление кэша пакетов после добавления нового репозитория
  - apt-get update -y

  ## Установка Docker Engine, CLI и Docker Compose
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  
  ## Включение автозапуска и запуск службы Docker
  - systemctl enable docker
  - systemctl start docker

  # Разворачивание SOCKS5
  ## Создаем каталоги и скачиваем файлы конфигурации 
  - mkdir -p /opt/3proxy/config

  - curl -sSL https://raw.githubusercontent.com/mapsvk/silver-note/refs/heads/main/project-timeweb/docker-compose.yml -o /opt/3proxy/docker-compose.yml
  - curl -sSL https://raw.githubusercontent.com/mapsvk/silver-note/refs/heads/main/project-timeweb/socks5/3proxy.cfg -o /opt/3proxy/config/3proxy.cfg

  ## Запускаем контейнер
  - cd /opt/3proxy && docker compose up -d

  ## Изоляция SOCKS5 и WireGuard между собой
  - iptables -I FORWARD -i wg0 -o br-+ -j REJECT
  - iptables -I FORWARD -i br-+ -o wg0 -j REJECT
