services:
  socks5:
    image: ghcr.io/tarampampam/3proxy:2
    container_name: socks5
    restart: always
    ports:
      - "1080:1080/tcp"
    volumes:
      - /opt/3proxy/config:/etc/3proxy:ro
    networks:
      - socks5_network
    ulimits:
      nofile:
        soft: 20000
        hard: 20000

networks:
  socks5_network:
    driver: bridge
